# Generated by Django 4.2.6 on 2023-10-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_profile_course_profile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Last_Name',
        ),
    ]
